---
title: "Test run for GCTB"
output: html_notebook
date: 08-16-2018
author: "Jinliang Yang"
---


```{r setup, include=TRUE}
#setwd("~/Documents/Github/pvpDiallel/")
knitr::opts_knit$set(root.dir=normalizePath('../../'))
```


### format phenotype for GCTB

```{r, eval=FALSE}
pheno <- read.csv("data/pheno_282set_n37.csv")


get_gctb_phen <- function(df, cols=4:5, outdir="largedata/gctb_pheno/"){
  # df: must contain "FID" (family id), "IID" (individual id)
  # cols: the idx of the phenotype columns
  
  for(i in cols){
    ### trait name
    tnm <- names(df)[i]
    out <- df[, c("FID", "IID", tnm)]
    ofile <- paste0("largedata/gctb_pheno/", tnm, ".phen")
    write.table(out, ofile, sep="\t", row.names=FALSE, col.names=FALSE, quote=FALSE)
  }
}

### 
m <- read.csv("data/BLUE_mineral_ziegler.csv")
names(m)[1] <- "IID"
m$FID <- "282set"

get_gctb_phen(df=m, cols=2:(ncol(m)-1), outdir="largedata/gctb_pheno/")

```


## Batch job using a GTCB wrapper in `huskeR`

```{r}
library("huskeR")

# gctb --bfile /common/jyanglab/jyang21/dbcenter/HapMap3/set282/allchr_bisnp_n282_snpid_maf001_geno1 
# --pheno largedata/gctb_pheno/Zn66.phen --bayes # NS --pi 0.05 --hsq 0.5 --S 0 --wind 0.1 --chain-length 410000 --burn-in 10000 --out largedata/bayesNS/test > largedata/bayesNS/test.log
ph <- list.files(path="largedata/gctb_pheno", pattern="phen", full.names =  TRUE)
out <- gsub("gctb_pheno", "bayesNS", ph)
out <- gsub(".phen", "", out)

df <- data.frame(bfile="/common/jyanglab/jyang21/dbcenter/HapMap3/set282/allchr_bisnp_n282_snpid_maf001_geno1",
                 pheno=ph,
                 pi=0.05,
                 hsq=0.5,
                 S=0,
                 wind=0.1,
                 chainlength=41000,
                 burnin=1000,
                 out=out,
                 log=paste0(out, ".log")
                 )

run_gctb(df, bayes="NS", shid="run_gtcb",
         email="yangjl0930@gmail.com", runinfo=c(FALSE, "jclarke", "1", "10G", "8:00:00"))

```


## Run BayesS:

```{r}
library("huskeR")

# gctb --bfile /common/jyanglab/jyang21/dbcenter/HapMap3/set282/allchr_bisnp_n282_snpid_maf001_geno1 
# --pheno largedata/gctb_pheno/Zn66.phen --bayes # NS --pi 0.05 --hsq 0.5 --S 0 --wind 0.1 --chain-length 410000 --burn-in 10000 --out largedata/bayesNS/test > largedata/bayesNS/test.log
ph <- list.files(path="largedata/gctb_pheno", pattern="phen", full.names =  TRUE)
out <- gsub("gctb_pheno", "bayesS", ph)
out <- gsub(".phen", "", out)

df <- data.frame(bfile="/common/jyanglab/jyang21/dbcenter/HapMap3/set282/allchr_bisnp_n282_snpid_maf001_geno1",
                 pheno=ph,
                 pi=0.05,
                 hsq=0.5,
                 S=0,
                 wind=0.1,
                 chainlength=41000,
                 burnin=1000,
                 out=out,
                 log=paste0(out, ".log")
                 )

run_gctb(df, bayes="S", shid="run_gtcb",
         email="yangjl0930@gmail.com", runinfo=c(FALSE, "jclarke", "1", "10G", "8:00:00"))








# Plot the densities of snps in the csv file for each chr seperately
library(ggplot2)
snpDensity<-ggplot(snpden) +
geom_histogram(aes(x=Freq),binwidth=1e3) + # pick a binwidth that is not too small 
facet_wrap(~ CHROM,ncol=2) + # seperate plots for each chr, x-scales can differ from chr to chr
ggtitle("SNP density using pruned data_maf0005_geno01_r2_01 (#3.08 million)") +
theme_update(plot.title = element_text(hjust = 0.5)) +
xlab("Position in the genome") + 
ylab("SNP density") + 
theme_bw() + # I prefer the black and white theme
 geom_hline(yintercept = 1000,col="red",size=0.5)



```


