---
title: "Grab GCTB parRes"
output: html_notebook
date: 08-19-2018
author: "Jinliang Yang"
---


```{r setup, include=TRUE}
#setwd("~/Documents/Github/pvpDiallel/")
knitr::opts_knit$set(root.dir=normalizePath('../../'))
```


### format phenotype for GCTB

```{r, eval=FALSE}
get_gctb_parres <- function(path="largedata/bayesS"){
  # df: must contain "FID" (family id), "IID" (individual id)
  # cols: the idx of the phenotype columns
  
  files <- list.files(path, pattern="parRes", full.names = TRUE)
  message(sprintf("###>>> [%s] files detected!", length(files)))
  
  res <- data.frame()
  for(i in 1:length(files)){
    ### read in the file by skip the first two rows:
    pres <- read.table(files[i], skip = 2)
    pres$par <- row.names(pres)
    pres$file <- files[i]
    pres$trait <- gsub(".*/|.parRes", "", pres$file)
    res <- rbind(res, pres)
  }
  return(res)
}

### 
out <- get_gctb_parres(path="largedata/bayesS")
s <- subset(out, par == "S")

pi <- subset(out, par == "Pi")

hsq <- subset(out, par == "hsq")
```




```{r}

library(cowplot)
library(ggplot2)
library("tidyr")
cbPalette=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  

files <- list.files(path="largedata/bayesS/", pattern = "Par", full.names = TRUE)
i=55

i=36
files[i]



df <- read.table(files[i], header=T)
df$mcmc <- 1:nrow(df)
df2 <- gather(df, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#df3 <- subset(df3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#df3$type <- "Micronutrient Traits"

#library(dplyr) 
fsize=16 
p1 <- ggplot(data=df2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteraction (Markov Chain Monte Carlo)") +
      ylab("")
p1
### output
pdf("graphs/trace_plot_numberoftilleringplants.pdf", width=8, height=12)
p1
dev.off()


```

