---
title: "Gctb_apgv4"
Date:09/21/2018
output: html_document
---

#GCTB analysis. Save filenames with .mpi extension.

```{bash}
#!/bin/sh

#SBATCH --job-name=T1_gctb

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=16

#SBATCH --time=50:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait1_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait1_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 1  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T1_gctb_test > T1_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 2  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out  T2_gctb_test > T2_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 3 --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T3_gctb_test> T3_gctb_test.log 2>&1


mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 4 --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T4_gctb_test > T4_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 5 --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T5_gctb_test > T5_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 6 --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T6_gctb_test> T6_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 7 --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out  T7_gctb_test > T7_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 8--bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T8_gctb_test > T8_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 9  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T9_gctb_test > T9_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 10  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T10_gctb_test> T10_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 11  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T11_gctb_test> T11_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 12  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T12_gctb_test > T12_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 13  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T13_gctb_test> T13_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 14  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T14_gctb_test > T14_gctb_test.log 2>&1


mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 15  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T15_gctb_test > T15_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 16  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T16_gctb_test> T16_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 17  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T17_gctb_test > T17_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 18  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T18_gctb_test > T18_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 19  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T19_gctb_test > T19_gctb_test.log 2>&1

mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUE_mineral_ziegler.txt --mpheno 20  --bayes S --pi 0.1 --hsq 0.5 --chain-length 25000 --burn-in 5000 --out T20_gctb_test > T20_gctb_test.log 2>&1


# For Boron
MCMC cycles completed.

Posterior statistics from MCMC samples:

              Mean  	      SD
        Pi    0.151669        0.012495
    NNZsnp    467167.812500   38496.179688
   SigmaSq    0.000001        0.000001
         S    0.000000        0.000000
    ResVar    0.224127        0.051960
    GenVar    0.069540        0.048620
       hsq    0.236292        0.161993

Analysis finished: Fri Sep 28 13:25:49 2018
Computational time: 96:31:53
```

```{r}
rm(list=ls())
#install.packages("cowplot")
library(cowplot)
library(ggplot2)
#install.packages("tidyr")
library("tidyr")

cbPalette=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  
df <- read.table("~/Ziegler_mineral_GWAS/data/apgv4/T1_gctb_test_30G.log", header=T)
tail(df)
df$mcmc <- 1:nrow(df)
df$mcmc <- df$mcmc *100
df2 <- gather(df, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#df3 <- subset(df3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#df3$type <- "Micronutrient Traits"
tail(df)
tail(df2)
#library(dplyr) 
fsize=16 
p1 <- ggplot(data=df2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p1
### output
pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_boron.pdf", width=8, height=12)
p1
dev.off()
                                                                                                                                                

```

```{bash}
#with 1100 iterations and 100 burn into get the results rom first run
[raghu@login.crane apgv4]$ tail T10_gctb_test_30G_run1.log
        Pi    0.104283        0.003531       
    NNZsnp    321111.593750   10811.239258   
   SigmaSq    0.000300        0.000013       
         S    0.000000        0.000000       
    ResVar    4.994203        1.312193       
    GenVar    12.199145       1.160608       
       hsq    0.711104        0.063557                         

##Get PCs using plink: Related documentation available at 
https://www.biostars.org/p/271694/
https://www.biostars.org/p/326758/

#By default plink produces 20 PCs, we can specify the number of PCs we need
plink --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pca 10 var-wts --out pca_maf0005_geno1_r201
6.5264
4.54309
3.94777
3.58171
3.48282
3.34786
3.18532
3.15261
3.08542
3.00943

```


#Principal Components

```{r}
eigen <- data.frame(read.table("pca_maf0005_geno1_r201.eigenvec", header=FALSE, skip=0, sep=" "))
rownames(eigen) <- eigen[,2]
eigen <- eigen[,3:ncol(eigen)]
#summary(eigen)

#Determine the proportion of variance of each component
proportionvariances <- ((apply(eigen, 1, sd)^2) / (sum(apply(eigen, 1, sd)^2)))*100

plot(eigen[,1], eigen[,2])


eigen <- eigen[,c(1:5)]
write.csv(eigen,"pca_maf0005_geno1_r201_top3_pcs.csv")


##screeplot of eigen value and pcs

df1=read.csv("~/Ziegler_mineral_GWAS/data/apgv4/eigen-values-pcs-as-cov.csv",header=T)

head(df1)

library(ggplot2)
p2 <-ggplot(df1,aes(x=df1$Principal.Component,y=(df1$Eigen.value))) + geom_line() + geom_point() +
  ggtitle("Screeplot of eigen values")+
  xlab("Principal Components") +
  ylab("eigen values") 
  
p2
pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/eigen-values.pdf",width=6.5, height=5)
p2
dev.off()

##Plot percent variance and cumulative variance of PCs

df2=read.csv("~/Ziegler_mineral_GWAS/data/apgv4/eigen-values and percent var.csv",header=T)

head(df2)

str(df2)

df2=df2[,-c(7:11)]

#https://stackoverflow.com/questions/11955229/how-to-change-the-default-font-size-in-ggplot2
theme_set(theme_gray(base_size = 16))

f1=ggplot(df2,aes(x=df2$X,y=df2$percent.of.variance)) + geom_line() + geom_point() +
  ggtitle("Percent variance explained by principal\n components")+
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Principal Components") +
  ylab("Percent Variance (%)") 
  

f2=ggplot(df2,aes(x=df2$X,y=df2$Cumulative.percent.variance)) + geom_line() + geom_point() +
  ggtitle("Cumulative variance explained by principal\n components")+
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Principal Components") +
  ylab("Cumulative Variance (%)") 

#install.packages ("gridExtra")
library(gridExtra)

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/Percent variance explained by PCs.pdf",width=12,height=7)
grid.arrange(f1,f2,nrow=1)
dev.off()








```

```{bash}
tr ',' '\t' < pca_maf0005_geno1_r201_top3_pcs.csv >pca_maf0005_geno1_r201_top3_pcs.txt #transform delimiter



awk '{$1=""; print $0}' pca_maf0005_geno1_r201_top3_pcs_new.txt >pca_maf0005_geno1_r201_top3_pcs.txt # to filter column

#Sample --covar file
'''[raghu@c0401.crane apgv4]$ head pca_maf0005_geno1_r201_top3_pcs_new.txt
FID  IID PC1 PC2 PC3
 282set 33-16 -0.0324919 -0.000606599 0.0244391
 282set 38-11Goodman-Buckler -0.0470689 -0.00570321 -0.00372294
 282set 4226 -0.0271548 -0.00105938 0.0199683
 282set 4722 -0.0404898 0.00682655 0.131463
 282set A6 0.0906579 0.0223418 -0.0178671
 282set A188 -0.0307402 -0.000959044 0.0322203
 282set A214NGoodman-Buckler -0.0377738 -0.00586757 -0.129892
 282set A239 -0.0395108 -0.00788368 -0.0116936
 282set A441-5 -0.00594948 0.0141381 0.016108'''
 
 
############################
#Changed gctb run for traits with moderate to high heritability and relatively more important
############################

#For Fe,m=10
 
#!/bin/sh

#SBATCH --job-name=T10_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait10_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait10_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T10_gctb_30G_run1_withpcs > T10_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1


############################

#For Zn,m=14

#!/bin/sh

#SBATCH --job-name=T14_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait14_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait14_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 14 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T14_gctb_30G_run1_withpcs > T14_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1

############################

#For Cu,m=13

#!/bin/sh

#SBATCH --job-name=T13_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait13_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait13_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 13 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T13_gctb_30G_run1_withpcs > T13_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1

##############################
#For Mn,m=9

#!/bin/sh

#SBATCH --job-name=T14_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait9_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait9_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 9 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T9_gctb_30G_run1_withpcs > T9_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1

#########################
#For Mo, m=19

#!/bin/sh

#SBATCH --job-name=T19_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait19_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait19_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 19 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T19_gctb_30G_run1_withpcs > T19_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1

#####################################
#For Mg,m=3

#!/bin/sh

#SBATCH --job-name=T3_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait3_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait3_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 3 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T3_gctb_30G_run1_withpcs > T3_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1


####################################
#For P,m=5

#!/bin/sh

#SBATCH --job-name=T5_n16_gctb

#SBATCH --ntasks=16

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=4G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait5_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait5_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0
#with top3 PCs as covariates
mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 5 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T5_gctb_30G_run1_withpcs > T5_gctb_30G_run1_withpcs.log 2>&1
#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.5 --chain-length 41000 --burn-in 10000 --out T10_gctb_30G_run2 > T10_gctb_30G_run2.log 2>&1



```

```{r}

cd /lustre/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

#Used the file T10_gctb_test_30G_run1_withpcs.snpRes file to subset the SNP effects affecting Fe concentration
  
library(data.table)
df2=fread("snpRes_Fe_run1.txt",header=F)

#colnames(df2) <-c("X","Name","Chrom","Position","Freq","Effect","SE")

##Between 0 and 0.01
df3=df2[which(Freq<=0.01),]
#Classes ‘data.table’ and 'data.frame':	1235044 obs. of  7 variables:
df3 <-  transform(df3, group=cut(Freq, breaks=c(-Inf, 0.001, 0.002, 0.003,0.004,0.005,0.006,0.007,0.008,0.009,0.01,Inf),
      labels=c(0,0.001,0.002,0.003,0.004,0.005,0.006,0.007,0.008,0.009,0.01)))

head(df3)

res2 <-do.call(data.frame,aggregate(df3$Effect~group, df3, 
        FUN=function(x) c(Count=length(x), Sum=sum(x))))

'''
group df3.Effect.Count df3.Effect.Sum
1     0            35569       0.089493
2 0.002           124161      -0.086862
3 0.004           175277      -0.210641
4 0.005           150358       0.195551
5 0.007           559040       0.150796
6 0.008              395       0.014149
7 0.009           190244      -0.467020
'''


##Between 0.01 to 0.1
df4=df2[which(Freq<=0.1),]
#Classes ‘data.table’ and 'data.frame':	2668950 obs. of  7 variables:
df4 <-  transform(df4, group=cut(Freq, breaks=c(-Inf, 0.01, 0.02, 0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,Inf),
      labels=c('<0.01',0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1)))

head(df4)

res3 <-do.call(data.frame,aggregate(df4$Effect~group, df4, 
        FUN=function(x) c(Count=length(x), Sum=sum(x))))

'''group df4.Effect.Count df4.Effect.Sum
1  <0.01          1235044      -0.314534
2   0.01           688760      -0.343754
3   0.02           264038      -0.189313
4   0.03           148900       0.028069
5   0.04           101646       0.331834
6   0.05            72271      -0.069616
7   0.06            55473       0.101053
8   0.07            42453       0.123751
9   0.08            33501       0.095844
10  0.09            26864      -0.001712'''

##Between 0.1 to 1

df5 <-  transform(df2, group=cut(Freq, breaks=c(-Inf, 0.1, 0.2, 0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,Inf),
      labels=c('<0.1',0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1)))

head(df5)

res4 <-do.call(data.frame,aggregate(df5$Effect~group, df5, 
        FUN=function(x) c(Count=length(x), Sum=sum(x))))

'''group df5.Effect.Count df5.Effect.Sum
1  <0.1          2668950      -0.238378
2   0.1           121637      -0.093653
3   0.2            44914       0.009517
4   0.3            53471      -0.174963
5   0.4           160452      -0.328161
6   0.5            30731       0.009011

library(ggplot2)
# Basic histogram
pdf("Effects_Fe_run1_001.pdf")
ggplot(res2, aes(x=group,y=df3.Effect.Sum)) + geom_bar(stat = "identity")
dev.off()


pdf("Effects_Fe_run1_01.pdf")
ggplot(res3, aes(x=group,y=df4.Effect.Sum)) + geom_bar(stat = "identity")
dev.off()


pdf("Effects_Fe_run1_1.pdf")
ggplot(res4, aes(x=group,y=df5.Effect.Sum)) + geom_bar(stat = "identity")
dev.off()

```

```{bash}
## chromosome-wise analysis of Fe trait

#!/bin/sh

#SBATCH --job-name=T10_run1_allchr

#SBATCH --ntasks=40

#SBATCH --time=20:00:00

#SBATCH --mem-per-cpu=5G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait10_allchr_run1.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_trait10_allchr_run1.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top4 PCs as covariates- First run

#mpirun -np 32 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno BLUEs_mineral_ziegler_complete.txt --mpheno 10 --covar pca_maf0005_geno1_r201_top3_pcs.txt  --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out T10_gctb_30G_run1_withpcs > T10_gctb_30G_r$

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 1 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_run2_chr1_top10pcs > Fe_chr1_top10pcs.log 2>&1
                                                                                                                                           mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 2 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr2_top10pcs > Fe_chr2_top10pcs.log 2>&1   
                                                                                                                                                                                                          
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 3 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr3_top10pcs > Fe_chr3_top10pcs.log 2>&1
                                                                                                                                          
                                                                                                                                            mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 4 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr4_top10pcs > Fe_chr4_top10pcs.log 2>&1  

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 5 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr5_top10pcs > Fe_chr5_top10pcs.log 2>&1 

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 6 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr6_top10pcs > Fe_chr6_top10pcs.log 2>&1
                                                                                                                                          mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 7 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr7_top10pcs > Fe_chr7_top10pcs.log 2>&1                     
                                                                                                                                          
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 8 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr8_top10pcs > Fe_chr8_top10pcs.log 2>&1
                                                                                                                                           mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 9 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr9_top10pcs > Fe_chr9_top10pcs.log 2>&1  

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 10 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 1100 --burn-in 100 --out Fe_chr10_top10pcs > Fe_chr10_top10pcs.log 2>&1 

#######################################################
#######################################################

##with top 10 PCs -Run2

#!/bin/sh

#SBATCH --job-name=T10_r2_c1

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c1.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c1.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 1 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.71  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr1_top10pcs > Fe_run2_chr1_top10pcs.log 2>&1



#!/bin/sh

#SBATCH --job-name=T10_r2_c2

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c2.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c2.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 2 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.08 --hsq 0.57  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr2_top10pcs > Fe_run2_chr2_top10pcs.log 2>&1   
                                                                                                                                            
#!/bin/sh

#SBATCH --job-name=T10_r2_c3

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c3.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c3.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates                                                              
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 3 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.08 --hsq 0.41  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr3_top10pcs > Fe_run2_chr3_top10pcs.log 2>&1
                                                                                                                                          

#!/bin/sh

#SBATCH --job-name=T10_r2_c4

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c4.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c4.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates         
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 4 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.67  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr4_top10pcs > Fe_run2_chr4_top10pcs.log 2>&1  



#!/bin/sh

#SBATCH --job-name=T10_r2_c5

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c5.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c5.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 5 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.71  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr5_top10pcs > Fe_run2_chr5_top10pcs.log 2>&1 



#!/bin/sh

#SBATCH --job-name=T10_r2_c6

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c6.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c6.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 6 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.59  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr6_top10pcs > Fe_run2_chr6_top10pcs.log 2>&1



#!/bin/sh

#SBATCH --job-name=T10_r2_c7

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c7.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c7.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 7 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.5  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr7_top10pcs > Fe_run2_chr7_top10pcs.log 2>&1                     



#!/bin/sh

#SBATCH --job-name=T10_r2_c8

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c8.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c8.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates                                                                                                                                          
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 8 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.65  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr8_top10pcs > Fe_run2_chr8_top10pcs.log 2>&1



#!/bin/sh

#SBATCH --job-name=T10_r2_c9

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c9.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c9.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 9 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.48  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr9_top10pcs > Fe_run2_chr9_top10pcs.log 2>&1  



#!/bin/sh

#SBATCH --job-name=T10_r2_c10

#SBATCH --ntasks=4

#SBATCH --time=30:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c10.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/Fe_run2_c10.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#with top10 PCs as covariates
mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --chr 10 --pheno BLUEs_mineral_rounded.txt  --mpheno 10 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.49  --chain-length 41000 --burn-in 1000 --out Fe_run2_chr10_top10pcs > Fe_run2_chr10_top10pcs.log 2>&1 

```

