---
title: "Pheno-37"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash}

#!/bin/sh

#SBATCH --job-name=X20wt_gctb

#SBATCH --ntasks=4 

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=8G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_x20wt_allchr.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_x20wt_allchr.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0


#without covariates

mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno  pheno_282_n37_new.txt --mpheno 37 --covar --bayes S --pi 0.1 --hsq 0.5 --chain-length 1100 --burn-in 100 --out X20wt_gctb_run1_withpcs > X20wt_gctb_run2.log 2>&1

#mpirun -np 16 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno  pheno_282_n37.txt --mpheno 9 --covar pca_maf0005_geno1_r201_top3_pcs.txt --bayes S --pi 0.1 --hsq 0.72 --chain-length 41000 --burn-in 1000 --out T10_gctb_30G_run2_withpcs > T10_gctb_3$
      
#nested Bayes S (following paramenters seem to work better)  
#try this approach
'''Options:

--bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1
--pheno pheno_282_n37_new.txt
--mpheno 37
--bayes NS
--wind 0.1
--pi 0.1
--hsq 0.5
--chain-length 5500
--burn-in 500
--out test_X20wt_gctb_run1_withpcs'''


mpirun -np 4 gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1 --pheno  pheno_282_n37_new.txt --mpheno 37 --bayes NS --wind 0.1 --pi 0.1 --hsq 0.5 --chain-length 5500 --burn-in 500 --out test_X20wt_gctb_run1_withpcs > test_X20wt_gctb_run1.log 2>&1


##Nested Bayes is a more complicated model. So I was suggested by Dr. Jian Yang to use Bayes S for our analysis.



```

```{bash}

## For KRN, No.of tillers per plant, protein and X20 weight respectively without and with PCs.

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 9 --bayes S --S 0.11  --pi 0.1 --hsq 0.73 --chain-length 41000 --burn-in 1000 --out KRN_gctb_run2_nopcs > KRN_gctb_run2_nopcs.log 2>&1

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 9 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --S 0.02 --hsq 0.77 --chain-length 41000 --burn-in 1000 --out KRN_gctb_run2_10pcs_rep > KRN_gctb_run2_10pcs_rep.log 2>&1	

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 22 --bayes S --pi 0.1 --hsq 0.6 --S -0.01 --chain-length 41000 --burn-in 1000 --out No_of_tillers_gctb_run2_nopcs > No_of_tillers_gctb_run2_nopcs.log 2>&1

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 22 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.55 --S -0.04 --chain-length 41000 --burn-in 1000 --out No_of_tillers_gctb_run2_10pcs > No_of_tillers_gctb_run2_10pcs.log 2>&1

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 20 --bayes S --pi 0.09 --hsq 0.7 --S -0.01 --chain-length 41000 --burn-in 1000 --out prot_gctb_run2_nopcs > prot_gctb_run2_nopcs.log 2>&1


gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset  --pheno  pheno_282_n37_new.txt --mpheno 20 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.68 --S 0.05 --chain-length 41000 --burn-in 1000 --out Prot_gctb_run2_10pcs_rep > Prot_gctb_run2_10pcs_rep.log 2>&1

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 37 --bayes S --pi 0.1 --hsq 0.82 --S -0.03 --chain-length 41000 --burn-in 1000 --out X20wt_gctb_run2_nopcs_rep > X20wt_gctb_run2_nopcs_rep.log 2>&1  

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 37 --covar pca_maf0005_geno1_r201_top10_pcs.txt --bayes S --pi 0.1 --hsq 0.8 --S 0.01 --chain-length 41000 --burn-in 1000 --out X20wt_gctb_run2_10pcs_rep > X20wt_gctb_run2_10pcs_rep.log 2>&1



```

```{r}

##KRN without PCs
rm(list=ls())
#install.packages("cowplot")
library(cowplot)
library(ggplot2)
#install.packages("tidyr")
library("tidyr")

cbPalette=c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
nopckrn <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/KRN_gctb_run2_nopcs.csv", header=T)
head(nopckrn)
colnames(nopckrn)
nopckrn$mcmc <- 1:nrow(nopckrn)
nopckrn$mcmc <- nopckrn$mcmc *100
nopckrn2 <- gather(nopckrn, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#nopckrn3 <- subset(nopckrn3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#nopckrn3$type <- "Micronutrient Traits"
tail(nopckrn)
tail(nopckrn2)
#library(dplyr) 
fsize=16 
p1 <- ggplot(data=nopckrn2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p1
### output
pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_KRN_nopcs.pdf", width=8, height=12)
p1
dev.off()

##No. of tillers withot PCs

nopcNOTP <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/No_of_tillers_gctb_run2_nopcs.csv", header=T)
head(nopcNOTP)
colnames(nopcNOTP)
nopcNOTP$mcmc <- 1:nrow(nopcNOTP)
nopcNOTP$mcmc <- nopcNOTP$mcmc *100
nopcNOTP2 <- gather(nopcNOTP, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#nopcNOTP3 <- subset(nopcNOTP3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#nopcNOTP3$type <- "Micronutrient Traits"
tail(nopcNOTP)
tail(nopcNOTP2)
#library(dplyr) 
fsize=16 
p2 <- ggplot(data=nopcNOTP2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p2

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_NOTP_nopcs.pdf", width=8, height=12)
p2
dev.off()  

## Protein without PCs
nopcprot <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/prot_gctb_run2_nopcs.csv", header=T)
head(nopcprot)
colnames(nopcprot)
nopcprot$mcmc <- 1:nrow(nopcprot)
nopcprot$mcmc <- nopcprot$mcmc *100
nopcprot2 <- gather(nopcprot, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#nopcprot3 <- subset(nopcprot3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#nopcprot3$type <- "Micronutrient Traits"
tail(nopcprot)
tail(nopcprot2)
#library(dplyr) 
fsize=16 
p3 <- ggplot(data=nopcprot2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p3

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_prot_nopcs.pdf", width=8, height=12)
p3
dev.off()  

##x20 wt without PCs
nopcx20 <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/X20wt_gctb_run2_nopcs_rep.csv", header=T)
head(nopcx20)
colnames(nopcx20)
nopcx20$mcmc <- 1:nrow(nopcx20)
nopcx20$mcmc <- nopcx20$mcmc *100
nopcx202 <- gather(nopcx20, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#nopcx203 <- subset(nopcx203, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#nopcx203$type <- "Micronutrient Traits"
tail(nopcx20)
tail(nopcx202)
#library(dplyr) 
fsize=16 
p6 <- ggplot(data=nopcx202, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p6

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_x20_nopcs.pdf", width=8, height=12)
p6
dev.off()  


##NOTP with 10 pcs 
tenpcNOTP <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/No_of_tillers_gctb_run2_10pcs.csv", header=T)
head(tenpcNOTP)
colnames(tenpcNOTP)
tenpcNOTP$mcmc <- 1:nrow(tenpcNOTP)
tenpcNOTP$mcmc <- tenpcNOTP$mcmc *100
tenpcNOTP2 <- gather(tenpcNOTP, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#tenpcNOTP3 <- subset(tenpcNOTP3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#tenpcNOTP3$type <- "Micronutrient Traits"
tail(tenpcNOTP)
tail(tenpcNOTP2)
#library(dplyr) 
fsize=16 
p4 <- ggplot(data=tenpcNOTP2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p4

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_NOTP_10pcs.pdf", width=8, height=12)
p4
dev.off()  

##x20 wt with 10PCs

tenpcx20wt <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/X20wt_gctb_run2_10pcs.csv", header=T)
head(tenpcx20wt)
colnames(tenpcx20wt)
tenpcx20wt$mcmc <- 1:nrow(tenpcx20wt)
tenpcx20wt$mcmc <- tenpcx20wt$mcmc *100
tenpcx20wt2 <- gather(tenpcx20wt, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#tenpcx20wt3 <- subset(tenpcx20wt3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#tenpcx20wt3$type <- "Micronutrient Traits"
tail(tenpcx20wt)
tail(tenpcx20wt2)
#library(dplyr) 
fsize=16 
p5<- ggplot(data=tenpcx20wt2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p5

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_X20wt_10pcs.pdf", width=8, height=12)
p5
dev.off()  

## KRN with 10 PCs
tenpckrn <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/KRN_gctb_run2_10pcs_rep.csv", header=T)
head(tenpckrn)
colnames(tenpckrn)
tenpckrn$mcmc <- 1:nrow(tenpckrn)
tenpckrn$mcmc <- tenpckrn$mcmc *100
tenpckrn2 <- gather(tenpckrn, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#tenpckrn3 <- subset(tenpckrn3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#tenpckrn3$type <- "Micronutrient Traits"
tail(tenpckrn)
tail(tenpckrn2)
#library(dplyr) 
fsize=16 
p7 <- ggplot(data=tenpckrn2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p7
### output
pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_KRN_10pcs.pdf", width=8, height=12)
p7
dev.off()


##Prot with 10 PCs
tenpcprot <- read.csv("~/Ziegler_mineral_GWAS/data/apgv4/Prot_gctb_run2_10pcs_rep.csv", header=T)
head(tenpcprot)
colnames(tenpcprot)
tenpcprot$mcmc <- 1:nrow(tenpcprot)
tenpcprot$mcmc <- tenpcprot$mcmc *100
tenpcprot2 <- gather(tenpcprot, parm, value, c("Pi", "NNZsnp", "S", "hsq"))
#tenpcprot3 <- subset(tenpcprot3, trait %in% c("Fe57", "Zn66", "Cu65", "Cd111"))
#tenpcprot3$type <- "Micronutrient Traits"
tail(tenpcprot)
tail(tenpcprot2)
#library(dplyr) 
fsize=16 
p8 <- ggplot(data=tenpcprot2, aes(x=mcmc, y=value, color=parm))+
        #geom_line(color=cbPalette[4])+
        geom_line()+
        
        facet_wrap( ~ factor(parm, levels=c("Pi", "NNZsnp", "S", "hsq"),
                         labels=c("Pi (Porportion of non-zero effect SNPs)", "Number of non-zero effect SNPs", "S (selection coefficient)", "SNP-based Heritability")), 
                          ncol=1, scales = 'free_y') +
        scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
        theme_bw() +
  guides(color=FALSE) +
        theme(#axis.text.x=element_blank(), axis.ticks.x=element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize),
          strip.text = element_text(size = fsize, face = "bold")) +
      xlab("Iteration (Markov Chain Monte Carlo)") +
      ylab("")
p8

pdf("~/Ziegler_mineral_GWAS/graphs/agpv4/trace_plot_prot_10pcs.pdf", width=8, height=12)
p8
dev.off()  






```

```{bash}
#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T1

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T1.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T1.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0
gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno pheno_282_n37_new.txt --mpheno 1 --bayes S --S  0.008272  --pi  0.092317  --hsq 0.811233  --chain-length 41000 --burn-in 1000   --out T1_gctb_run2_nopcs  > T1_gctb_run2_nopcs.log 2>&1

#################
#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T2

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T2.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T2.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno pheno_282_n37_new.txt --mpheno 2 --bayes S --S  -0.048336  --pi  0.088886  --hsq 0.703981  --chain-length 41000 --burn-in 1000   --out T2_gctb_run2_nopcs  > T2_gctb_run2_nopcs.log 2>&1

###################

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T3

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T3.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T3.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno pheno_282_n37_new.txt --mpheno 3 --bayes S --S  -0.034279  --pi  0.098322  --hsq 0.944963  --chain-length 41000 --burn-in 1000   --out T3_gctb_run2_nopcs  > T3_gctb_run2_nopcs.log 2>&1

##################

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T4

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T4.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T4.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 4 --bayes S --S  -0.040693  --pi  0.094314  --hsq 0.946572  --chain-length 41000 --burn-in 1000   --out T4_gctb_run2_nopcs  > T4_gctb_run2_nopcs.log 2>&1

####################
#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T5

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T5.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T5.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 5 --bayes S --S  0.015205  --pi  0.099766  --hsq 0.832379  --chain-length 41000 --burn-in 1000   --out T5_gctb_run2_nopcs  > T5_gctb_run2_nopcs.log 2>&1




#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T6

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T6.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T6.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 6 --bayes S --S  0.062138  --pi  0.100149  --hsq 0.900306  --chain-length 41000 --burn-in 1000   --out T6_gctb_run2_nopcs  > T6_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T7

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T7.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T7.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 7 --bayes S --S  -0.023113  --pi  0.098421  --hsq 0.726865  --chain-length 41000 --burn-in 1000   --out T7_gctb_run2_nopcs  > T7_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T8

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T8.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T8.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 8 --bayes S --S  0.025387  --pi  0.094  --hsq 0.632489  --chain-length 41000 --burn-in 1000   --out T8_gctb_run2_nopcs  > T8_gctb_run2_nopcs.log 2>&1

#!/bin/sh


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T10

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T10.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T10.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 10 --bayes S --S  0.019376  --pi  0.098188  --hsq 0.791913  --chain-length 41000 --burn-in 1000   --out T10_gctb_run2_nopcs  > T10_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T11

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T11.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T11.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 11 --bayes S --S  0.028373  --pi  0.105309  --hsq 0.674668  --chain-length 41000 --burn-in 1000   --out T11_gctb_run2_nopcs  > T11_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T12

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T12.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T12.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 12 --bayes S --S  -0.075865  --pi  0.098731  --hsq 0.94171  --chain-length 41000 --burn-in 1000   --out T12_gctb_run2_nopcs  > T12_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T13

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T13.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T13.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 13 --bayes S --S  0.010151  --pi  0.099781  --hsq 0.943095  --chain-length 41000 --burn-in 1000   --out T13_gctb_run2_nopcs  > T13_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T14

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T14.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T14.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 14 --bayes S --S  0.029345  --pi  0.092755  --hsq 0.645222  --chain-length 41000 --burn-in 1000   --out T14_gctb_run2_nopcs  > T14_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T15

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T15.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T15.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 15 --bayes S --S  -0.05888  --pi  0.096277  --hsq 0.917285  --chain-length 41000 --burn-in 1000   --out T15_gctb_run2_nopcs  > T15_gctb_run2_nopcs.log 2>&1





#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T16

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T16.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T16.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 16 --bayes S --S  0.05494  --pi  0.101781  --hsq 0.902792  --chain-length 41000 --burn-in 1000   --out T16_gctb_run2_nopcs  > T16_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T17

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T17.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T17.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 17 --bayes S --S  0.01726  --pi  0.10134  --hsq 0.767805  --chain-length 41000 --burn-in 1000   --out T17_gctb_run2_nopcs  > T17_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T18

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T18.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T18.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 18 --bayes S --S  0  --pi  0.103433  --hsq 0.871782  --chain-length 41000 --burn-in 1000   --out T18_gctb_run2_nopcs  > T18_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T19

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T19.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T19.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 19 --bayes S --S  -0.042315  --pi  0.10602  --hsq 0.80926  --chain-length 41000 --burn-in 1000   --out T19_gctb_run2_nopcs  > T19_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T21

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T21.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T21.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0  

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 21 --bayes S --S  0.059708  --pi  0.102679  --hsq 0.673413  --chain-length 41000 --burn-in 1000   --out T21_gctb_run2_nopcs  > T21_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T23

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T23.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T23.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 23 --bayes S --S  0.014706  --pi  0.100699  --hsq 0.858011  --chain-length 41000 --burn-in 1000   --out T23_gctb_run2_nopcs  > T23_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T24

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T24.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T24.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 24 --bayes S --S  -0.043207  --pi  0.09821  --hsq 0.564445  --chain-length 41000 --burn-in 1000   --out T24_gctb_run2_nopcs  > T24_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T25

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T25.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T25.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 25 --bayes S --S  -0.002683  --pi  0.095325  --hsq 0.883834  --chain-length 41000 --burn-in 1000   --out T25_gctb_run2_nopcs  > T25_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T26

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T26.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T26.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 26 --bayes S --S  -0.028955  --pi  0.102274  --hsq 0.62355  --chain-length 41000 --burn-in 1000   --out T26_gctb_run2_nopcs  > T26_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T27

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T27.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T27.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 27 --bayes S --S  0.015135  --pi  0.093968  --hsq 0.888304  --chain-length 41000 --burn-in 1000   --out T27_gctb_run2_nopcs  > T27_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T28

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T28.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T28.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 28 --bayes S --S  -0.021944  --pi  0.100251  --hsq 0.778557  --chain-length 41000 --burn-in 1000   --out T28_gctb_run2_nopcs  > T28_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T29

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T29.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T29.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 29 --bayes S --S  -0.002911  --pi  0.100987  --hsq 0.706562  --chain-length 41000 --burn-in 1000   --out T29_gctb_run2_nopcs  > T29_gctb_run2_nopcs.log 2>&1

#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T30

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T30.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T30.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 30 --bayes S --S  0.011188  --pi  0.094703  --hsq 0.562193  --chain-length 41000 --burn-in 1000   --out T30_gctb_run2_nopcs  > T30_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T31

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T31.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T31.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 31 --bayes S --S  0.037821  --pi  0.108641  --hsq 0.839885  --chain-length 41000 --burn-in 1000   --out T31_gctb_run2_nopcs  > T31_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T32

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T32.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T32.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 32 --bayes S --S  0.008942  --pi  0.104051  --hsq 0.859548  --chain-length 41000 --burn-in 1000   --out T32_gctb_run2_nopcs  > T32_gctb_run2_nopcs.log 2>&1


#!/bin/sh

#SBATCH --job-name=gctb_nopcs_T33

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T33.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T33.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 33 --bayes S --S  0.047282  --pi  0.095868  --hsq 0.882024  --chain-length 41000 --burn-in 1000   --out T33_gctb_run2_nopcs  > T33_gctb_run2_nopcs.log 2>&1


#!/bin/sh
#SBATCH --job-name=gctb_nopcs_T34

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T34.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T34.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 34 --bayes S --S  -0.05198  --pi  0.098167  --hsq 0.62348  --chain-length 41000 --burn-in 1000   --out T34_gctb_run2_nopcs  > T34_gctb_run2_nopcs.log 2>&1

#!/bin/sh
#SBATCH --job-name=gctb_nopcs_T35

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T35.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T35.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 35 --bayes S --S  0.021662  --pi  0.098119  --hsq 0.63459  --chain-length 41000 --burn-in 1000   --out T35_gctb_run2_nopcs  > T35_gctb_run2_nopcs.log 2>&1


#!/bin/sh
#SBATCH --job-name=gctb_nopcs_T36

#SBATCH --ntasks=1

#SBATCH --time=100:00:00

#SBATCH --mem-per-cpu=20G

#SBATCH --error=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T36.err
#SBATCH --output=/work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/slurm-log/apgv4/gctb_run2_nopcs_T36.out

cd /work/jyanglab/raghu/jyang/projects/Ziegler_mineral_GWAS/largedata/apgv4/

module load compiler/gcc/4.9 openmpi/1.10 gctb/1.0

gctb --bfile pruned_r2_01_allchr_agpv4_n282_snpid_maf0005_geno1_maf001subset --pheno  pheno_282_n37_new.txt --mpheno 36 --bayes S --S  0.029536  --pi  0.102347  --hsq 0.863014  --chain-length 41000 --burn-in 1000   --out T36_gctb_run2_nopcs  > T36_gctb_run2_nopcs.log 2>&1





```

